### ISSUE TITLE
Shibboleth package Member of Not Working

### ISSUE THREAD

**Issue by marishaS** [uisits/ui#4]
Hi @ChinwalPrasad, 

The shibboleth config file ``` entitlement``` key needs to be updated to ``` isMemberOf ```.

**Comment by ChinwalPrasad** [comment]
Thanks for reporting @marishaS. I'll fix this in the next release.

**Comment by ChinwalPrasad** [comment]
@marishaS Fixed this in https://github.com/uisits/ui/commit/4a13184785e3c361a7cd83f80d41a6f5fea46ef1
